[backdrop]
enabled = true

[bar.default]
auto_hide = true
capsule = true
center = [ "clock", "wallpaper" ]
end = [ "tray", "notifications", "clipboard", "network", "bluetooth", "volume", "brightness", "battery", "control-center" ]
margin_edge = 0
margin_ends = 0
radius = 0
reserve_space = false
start = [ "workspaces", "media" ]
thickness = 32

[shell.panel]
launcher_categories = false
launcher_compact = true
open_near_click_control_center = true

[shell.screen_corners]
enabled = true
size = 8

[theme]
builtin = "Catppuccin"
mode = "dark"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "kcolorscheme", "qt" ]

[weather]
enabled = false
